name: eip712
description: Dart implementation of EIP-712 (Ethereum typed structured data hashing and signing) that enables type-safe signing of structured data with Ethereum wallets.
version: 1.0.1
homepage: https://variance.space
repository: https://github.com/vaariance/eip-712
issue_tracker: https://github.com/vaariance/eip-712/issues

environment:
  sdk: ^3.7.2

dependencies:
  wallet: ^0.0.18
  web3dart: ^3.0.1
  json_annotation: ^4.9.0
  freezed_annotation: ^3.1.0

dev_dependencies:
  build_runner: ^2.10.4
  freezed: ^3.2.3
  json_serializable: ^6.11.2
  lints: ^6.0.0
  test: ^1.28.0

topics:
  - ethereum
  - sign-typed-data
  - eip-712